version: "3"

services:
  node-api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: nodeapi
    restart: unless-stopped
    environment:
      - MONGO_HOSTNAME=database
    ports:
      - "8080:3000"
    container_name: nodeenv
    entrypoint: "bash start.sh"
    volumes:
    - ./:/node-app
    depends_on: 
      - database

  database:
    image: mongo:latest
    container_name: mongo-cont
    restart: always 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGO_INITDB_DATABASE=test
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - ./data/db/:/data/db



